/**
 * controller.c  --  Closed-loop position control.
 *
 * Implements the full behaviour from the project write-up:
 *   - PD control on encoder position
 *   - startup boost            (break static friction / take up backlash)
 *   - deadzone compensation    (guarantee a command actually produces motion)
 *   - velocity-aware arrival   (on target only when close AND stopped)
 *   - software limits          (targets clamped to travel range)
 *   - homing-settle calibration(seek stop -> settle -> zero -> back off)
 *
 * Sign convention: positive PWM must increase the encoder count. If your
 * wiring is opposite, set MOTOR_INVERT in config.h -- do not edit this file.
 */
#include "main.h"
#include "controller.h"
#include "motor.h"
#include "encoder.h"

/* ------------------------------------------------------------ module state */
static volatile ctrl_state_t state = ST_DISABLED;

static int32_t target       = 0;
static int32_t position     = 0;
static int32_t last_position= 0;
static float   velocity     = 0.0f;   /* filtered, counts/tick               */
static float   last_pwm     = 0.0f;   /* last applied signed duty            */

static int32_t arrive_count = 0;      /* debounce for arrival               */
static int32_t boost_left   = 0;      /* remaining startup-boost ticks       */

/* homing bookkeeping */
static int32_t home_ticks   = 0;
static int32_t home_stall   = 0;
static int32_t settle_ticks = 0;
static int     home_moved   = 0;

/* ------------------------------------------------------------------ helpers */
static inline int32_t iabs32(int32_t v) { return v < 0 ? -v : v; }
static inline float   fabsf_(float v)   { return v < 0.0f ? -v : v; }

static void apply_output(float u)
{
    if (u >  PWM_MAX_CMD) u =  PWM_MAX_CMD;
    if (u < -PWM_MAX_CMD) u = -PWM_MAX_CMD;
    last_pwm = u;
    motor_set(u);
}

/* Core PD + practical compensations, used in MOVING and HOLDING. */
static void run_position_control(void)
{
    int32_t error = target - position;
    int32_t aerr  = iabs32(error);
    float   avel  = fabsf_(velocity);

    /* ---- velocity-aware arrival detection ---- */
    if (aerr <= POS_TOL && avel <= VEL_TOL) {
        if (++arrive_count >= ARRIVE_DEBOUNCE) {
            state = ST_HOLDING;
        }
    } else {
        arrive_count = 0;
        /* if we drifted well outside tolerance while holding, resume moving */
        if (state == ST_HOLDING && aerr > (POS_TOL + POS_HYST)) {
            state     = ST_MOVING;
            boost_left = BOOST_TICKS;   /* re-arm the kick for the new move   */
        }
    }

    /* ---- PD control law ---- */
    float u = (KP * (float)error) - (KD * velocity);

    if (aerr > POS_TOL) {
        /* ---- startup boost: kick while off-target but not yet moving ---- */
        if (boost_left > 0 && avel < STALL_VEL) {
            float kick = (error > 0) ? BOOST_PWM : -BOOST_PWM;
            if (fabsf_(kick) > fabsf_(u)) u = kick;
        }
        if (boost_left > 0) boost_left--;

        /* ---- deadzone compensation: enforce a minimum effective duty ---- */
        if (u > 0.0f && u <  MIN_MOVE_PWM) u =  MIN_MOVE_PWM;
        if (u < 0.0f && u > -MIN_MOVE_PWM) u = -MIN_MOVE_PWM;
    }

    apply_output(u);
}

/* ---- homing-settle calibration ---- */
static void run_homing_seek(void)
{
    apply_output(HOME_DIR * HOME_PWM);
    home_ticks++;

    if (fabsf_(velocity) > HOME_STALL_VEL) home_moved = 1;

    /* Confirm the stop only after an initial spin-up and after real motion,
     * so we do not mistake the standstill at t=0 for the hard stop.        */
    if (home_ticks > HOME_MIN_SEEK_TICKS && home_moved &&
        fabsf_(velocity) < HOME_STALL_VEL) {
        if (++home_stall >= HOME_STALL_DEBOUNCE) {
            motor_coast();
            last_pwm     = 0.0f;
            settle_ticks = HOME_SETTLE_TICKS;
            state        = ST_HOMING_SETTLE;
            return;
        }
    } else {
        home_stall = 0;
    }

    if (home_ticks > HOME_TIMEOUT_TICKS) {   /* safety: never found a stop */
        motor_coast();
        last_pwm = 0.0f;
        state    = ST_DISABLED;
    }
}

static void run_homing_settle(void)
{
    motor_coast();
    last_pwm = 0.0f;
    if (--settle_ticks <= 0) {
        /* Define this mechanical stop as zero, then back off it. */
        encoder_set(HOME_ZERO_VALUE);
        position      = HOME_ZERO_VALUE;
        last_position = position;
        velocity      = 0.0f;
        arrive_count  = 0;
        boost_left    = BOOST_TICKS;
        target        = HOME_ZERO_VALUE + HOME_BACKOFF;
        state         = ST_MOVING;
    }
}

/* ============================================================ real-time loop */
void controller_tick(void)
{
    /* 1) sample position and estimate velocity (EMA-filtered per-tick delta) */
    position = encoder_read();
    float raw_vel = (float)(position - last_position);       /* counts/tick   */
    velocity += VEL_FILTER_ALPHA * (raw_vel - velocity);
    last_position = position;

    /* 2) safety: if we somehow run past a hard limit, stop driving into it  */
    if (state == ST_MOVING || state == ST_HOLDING) {
        if (position < POS_MIN - POS_HYST || position > POS_MAX + POS_HYST) {
            motor_coast();
            last_pwm = 0.0f;
            return;
        }
    }

    /* 3) run the active behaviour */
    switch (state) {
        case ST_DISABLED:      motor_coast(); last_pwm = 0.0f; break;
        case ST_HOMING_SEEK:   run_homing_seek();              break;
        case ST_HOMING_SETTLE: run_homing_settle();            break;
        case ST_MOVING:
        case ST_HOLDING:       run_position_control();         break;
        default:               motor_coast(); last_pwm = 0.0f; break;
    }
}

/* ================================================================ commands */
void controller_init(void)
{
    state        = ST_DISABLED;
    position     = encoder_read();
    last_position= position;
    target       = position;
    velocity     = 0.0f;
    last_pwm     = 0.0f;
    arrive_count = 0;
    boost_left   = 0;
    motor_coast();
}

void controller_home(void)
{
    home_ticks = 0;
    home_stall = 0;
    home_moved = 0;
    state      = ST_HOMING_SEEK;
}

void controller_set_target(int32_t counts)
{
    if (state == ST_HOMING_SEEK || state == ST_HOMING_SETTLE) return; /* busy */

    if (counts < POS_MIN) counts = POS_MIN;   /* software limits */
    if (counts > POS_MAX) counts = POS_MAX;

    target       = counts;
    arrive_count = 0;
    boost_left   = BOOST_TICKS;                /* arm the startup kick */
    state        = ST_MOVING;
}

void controller_nudge(int32_t delta)
{
    /* nudge relative to the current target; ignored mid-homing by set_target */
    controller_set_target(target + delta);
}

void controller_stop(void)
{
    if (state == ST_HOMING_SEEK || state == ST_HOMING_SETTLE) {
        state = ST_DISABLED;                   /* abort homing safely */
        motor_coast();
        last_pwm = 0.0f;
        return;
    }
    target       = position;                   /* hold where we are */
    arrive_count = 0;
    state        = ST_HOLDING;
}

void controller_disable(void)
{
    state = ST_DISABLED;
    motor_coast();
    last_pwm = 0.0f;
}

void controller_enable(void)
{
    position     = encoder_read();
    last_position= position;
    target       = position;
    velocity     = 0.0f;
    arrive_count = 0;
    state        = ST_HOLDING;
}

/* =============================================================== telemetry */
ctrl_state_t controller_state(void)     { return state; }
int32_t      controller_target(void)    { return target; }
int32_t      controller_position(void)  { return position; }
int32_t      controller_error(void)     { return target - position; }
int32_t      controller_pwm(void)       { return (int32_t)last_pwm; }
int32_t      controller_velocity_cps(void)
{
    return (int32_t)(velocity * (float)CONTROL_HZ);   /* counts/tick -> /sec */
}

const char *controller_state_name(void)
{
    switch (state) {
        case ST_DISABLED:      return "DISABLED";
        case ST_HOMING_SEEK:   return "HOMING_SEEK";
        case ST_HOMING_SETTLE: return "HOMING_SETTLE";
        case ST_MOVING:        return "MOVING";
        case ST_HOLDING:       return "HOLDING";
        default:               return "?";
    }
}
